name: aham_ai_chat
description: A Flutter chat application with AI capabilities

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and fonts
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.18
  
  # Awesome icons
  font_awesome_flutter: ^10.6.0
  flutter_svg: ^2.0.7
  
  # Image handling
  image_picker: ^1.0.4
  
  # Network and data
  http: ^1.1.0
  path_provider: ^2.1.1
  
  # File operations
  file_picker: ^6.1.1
  archive: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true